name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - skdudgns
  pull_request:
    branches:
      - master
      - skdudgns

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_NAME: teamproject
      DB_USER: root
      DB_PASSWORD: 1234
      DB_HOST: 127.0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y mysql-server
          sudo service mysql start
          sleep 10
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ env.DB_PASSWORD }}'; FLUSH PRIVILEGES;"
          sudo mysql -u root -p${{ env.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.DB_NAME }};"

      - name: Run migrations
        env:
          DATABASE_URL: mysql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}/${{ env.DB_NAME }}
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: mysql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}/${{ env.DB_NAME }}
        run: |
          source venv/bin/activate
          python manage.py test

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend build
        run: |
          cd frontend
          npm run build
